// Atlas Assessment — L0/L1/L2 held-row activation applier (lane/l0-l2-activation).
//
// ATLAS merged the three click-image formats (#71) + serve-time per-tile minting
// (#77), so every answer format is now wired end-to-end. This applier ACTIVATES
// the flip-ready held rows in one atomic UPDATE each:
//
//     update questions
//        set format = <target>, content = <full activated jsonb>, is_active = true
//      where tenant + external_id matches AND is_active = false
//
// Atomic per the questions_held_rows_inactive guardrail: the activated content
// carries NO _authoring.requires_format_swap (image formats keep only
// _authoring.answer_model), so is_active=true is valid the instant it is set.
//
// PURELY ADDITIVE / NON-DESTRUCTIVE: writes ONE new migration + a mirrored
// seed.sql block; never rewrites a committed migration or the overlay-load
// blocks. Asserts every emitted external_id is one of the activation overlays'
// task keys (so a stray id can never escape the targeted set).
//
// Consumes the per-level activation overlays that exist (authored separately,
// never folded across levels):
//   overlay/l0a-activation.json, l0b-activation.json, l0c-activation.json,
//   overlay/l1-activation.json, overlay/l2-activation.json
//
// Run: pnpm convert:apply-activation

import { readFile, writeFile, access } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, "..", "..");
const OVERLAY_DIR = path.join(HERE, "overlay");
const OVERLAY_FILES = [
  "l0a-activation.json",
  "l0b-activation.json",
  "l0c-activation.json",
  "l1-activation.json",
  "l2-activation.json",
].map((f) => path.join(OVERLAY_DIR, f));
const SEED_FILE = path.join(REPO_ROOT, "supabase", "seed.sql");
const MIGRATIONS_DIR = path.join(REPO_ROOT, "supabase", "migrations");

const LOAD_TS = "20260617120000";
const LOAD_FILE = `${LOAD_TS}_l0_l2_activation.sql`;

const TENANT_SLUG = "inspirea_singapore_math";
const SEED_BEGIN = "-- BEGIN l0-l2-activation (lane/l0-l2-activation — do not hand-edit; pnpm convert:apply-activation)";
const SEED_END = "-- END l0-l2-activation";

interface ActivationTask {
  level: string;
  format: string;
  content: Record<string, unknown>;
  guard?: { is_active?: boolean };
}
interface ActivationOverlay {
  tasks: Record<string, ActivationTask>;
}

function sqlString(text: string): string {
  return `'${text.replace(/'/g, "''")}'`;
}
function sqlJsonb(value: Record<string, unknown>): string {
  return `${sqlString(JSON.stringify(value))}::jsonb`;
}

function buildUpdate(externalId: string, task: ActivationTask): string {
  const guardActive = task.guard?.is_active ?? false;
  return [
    `-- ${externalId} → ${task.format} (level ${task.level})`,
    `with t as (select id from tenants where slug = ${sqlString(TENANT_SLUG)})`,
    `update questions q`,
    `set format = ${sqlString(task.format)}::question_format,`,
    `    content = ${sqlJsonb(task.content)},`,
    `    is_active = true`,
    `from t`,
    `where q.tenant_id = t.id`,
    `  and q.external_id = ${sqlString(externalId)}`,
    `  and q.is_active = ${String(guardActive)};`,
  ].join("\n");
}

async function exists(p: string): Promise<boolean> {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

async function loadTasks(): Promise<Array<[string, ActivationTask]>> {
  const all: Array<[string, ActivationTask]> = [];
  const seen = new Set<string>();
  for (const file of OVERLAY_FILES) {
    if (!(await exists(file))) continue;
    const overlay = JSON.parse(await readFile(file, "utf8")) as ActivationOverlay;
    for (const [id, task] of Object.entries(overlay.tasks)) {
      if (seen.has(id)) throw new Error(`duplicate external_id across activation overlays: ${id}`);
      seen.add(id);
      all.push([id, task]);
    }
  }
  all.sort((a, b) => a[0].localeCompare(b[0]));
  return all;
}

/** Every SAM-* id literal in the emitted SQL must be one of the activation task keys. */
function verifyTargetedOnly(sql: string, allowed: Set<string>): void {
  const ids = sql.match(/SAM-L\d+[A-Z]?-Q\d+/g) ?? [];
  const stray = [...new Set(ids)].filter((id) => !allowed.has(id));
  if (stray.length > 0) {
    throw new Error(`non-destruction violated: emitted SQL references non-targeted ids: ${stray.join(", ")}`);
  }
}

function header(): string[] {
  return [
    "-- Atlas Assessment — L0/L1/L2 held-row activation (lane/l0-l2-activation).",
    "--",
    "-- Generated by scripts/conversion/apply-activation.ts from the per-level",
    "-- overlay/l*-activation.json files. Do not hand-edit.",
    "--",
    "-- Atomic activation of flip-ready held rows after #71 (image formats) + #77",
    "-- (per-tile minting): each UPDATE sets the real format + full render/answer",
    "-- content + is_active=true, guarded on is_active=false (idempotent). The",
    "-- activated content carries no _authoring.requires_format_swap, so the",
    "-- questions_held_rows_inactive CHECK permits is_active=true.",
    "--",
    "-- AGENTS.md §11 parity: prod path; identical statements mirrored into",
    "-- seed.sql in the l0-l2-activation block (idempotent guards).",
    "--",
    "-- PRECONDITION: the per-question images in the upload manifest must be in the",
    "-- private question-images bucket before this runs live, or an activated",
    "-- image row 500s at serve (signed-URL mint throws on a missing object).",
    "",
  ];
}

async function main(): Promise<void> {
  const tasks = await loadTasks();
  if (tasks.length === 0) {
    process.stderr.write("[apply-activation] no activation overlays found — nothing to do\n");
    return;
  }
  const allowed = new Set(tasks.map(([id]) => id));
  const updates = tasks.map(([id, task]) => buildUpdate(id, task));

  const migration = [...header(), ...updates.flatMap((s) => [s, ""])].join("\n");
  const seedBlock = [
    SEED_BEGIN,
    `-- MIRRORS supabase/migrations/${LOAD_FILE} (dev/CI path). Idempotent.`,
    "",
    ...updates.flatMap((s) => [s, ""]),
    SEED_END,
  ].join("\n");

  verifyTargetedOnly(migration, allowed);
  verifyTargetedOnly(seedBlock, allowed);

  await writeFile(path.join(MIGRATIONS_DIR, LOAD_FILE), `${migration}\n`, "utf8");

  const seedBefore = await readFile(SEED_FILE, "utf8");
  let seedAfter: string;
  const begin = seedBefore.indexOf(SEED_BEGIN);
  if (begin !== -1) {
    const end = seedBefore.indexOf(SEED_END, begin);
    if (end === -1) throw new Error("seed.sql has BEGIN l0-l2-activation without END");
    seedAfter = seedBefore.slice(0, begin) + seedBlock + seedBefore.slice(end + SEED_END.length);
  } else {
    const sep = seedBefore.endsWith("\n") ? "\n" : "\n\n";
    seedAfter = `${seedBefore}${sep}${seedBlock}\n`;
  }
  await writeFile(SEED_FILE, seedAfter, "utf8");

  process.stdout.write(
    [
      "[apply-activation] done",
      `  migration: ${LOAD_FILE}`,
      `  activations: ${String(tasks.length)} (${tasks.map(([id]) => id).join(", ")})`,
      `  seed.sql: l0-l2-activation block ${begin !== -1 ? "replaced" : "appended"}`,
      "  non-destruction: emitted SQL references only the activation task ids (asserted)",
      "",
    ].join("\n"),
  );
}

main().catch((err: unknown) => {
  process.stderr.write(`[apply-activation] FAILED: ${String(err)}\n`);
  process.exitCode = 1;
});
