// Atlas Assessment — regenerate the seed.sql activation-mirror region from migrations.
//
// SINGLE-SOURCE (reduce the hand-copy surface): the "restored activation-mirrors"
// region of seed.sql is MACHINE-DERIVED from the listed migration bodies, not hand-
// edited. Adding a new hand-written activation migration = drop the file + add its
// name to MIRROR_LIST + run `pnpm seed:regen-activations`. The parity guard
// (seed-activation-parity) then verifies nothing is missing.
//
// SCOPE: this regenerates ONLY the mechanical majority — the per-row activation /
// correction migrations whose seed mirror is a verbatim copy of the migration body.
// The applier-managed blocks (l0-l2-activation, l0/l1/l2-overlay, l1-art-activation,
// stage4, l1-q01-q07-activation) are regenerated by THEIR OWN tools (apply-activation.ts,
// apply-l0-overlay.ts, …) and are intentionally NOT touched here. The parity guard
// covers BOTH regions.
//
// Idempotent: replaces the content between the GENERATED markers (or, on first run,
// the hand-restored region) in place. Run: `pnpm seed:regen-activations`.

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, "..", "..");
const MIG = path.join(REPO_ROOT, "supabase", "migrations");
const SEED = path.join(REPO_ROOT, "supabase", "seed.sql");

const GEN_BEGIN = "-- BEGIN GENERATED activation-mirrors (pnpm seed:regen-activations — DO NOT HAND-EDIT)";
const GEN_END = "-- END GENERATED activation-mirrors";
const QA_MARKER_RE = /\n-- =+\n-- LOCAL-DEV QA SEED/;

// Ordered list: taxonomy NODES first, then row activations/corrections, then short
// flips. Each entry: [seed-block-name, migration filename]. The l0b-q03-q06 body is
// in 20260620150000_l0b_q03_q06_activation.sql until PR #109 renames the file to
// 150001 — resolved dynamically below so this works pre- or post-rename.
const MIRROR_LIST: Array<[string, string]> = [
  ["l0a-taxonomy-activation", "20260620120001_l0a_taxonomy_activation.sql"],
  ["l0c-taxonomy-activation", "20260620140000_l0c_taxonomy_activation.sql"],
  ["l0b-position-activation", "20260620130000_l0b_position_activation.sql"],
  ["l3-image-activation", "20260619100000_l3_image_activation.sql"],
  ["l4-image-activation", "20260619110000_l4_image_activation.sql"],
  ["l0a-q15-activation", "20260620150000_l0a_q15_activation.sql"],
  ["l0b-q03-q06-activation", "20260620150000_l0b_q03_q06_activation.sql"],
  ["l0a-q17-activation", "20260620160000_l0a_q17_activation.sql"],
  ["l2-q17-metadata-fix", "20260619090000_fix_l2_q17_metadata.sql"],
  ["audit-l2-fixes", "20260619050000_audit_L2_fixes.sql"],
  ["audit-l3plus-fixes", "20260619060000_audit_L3plus_fixes.sql"],
  ["l1-l4-short-eligible-backfill", "20260619080000_l1_l4_short_eligible_backfill.sql"],
];

/** Resolve a listed migration filename, tolerating the PR #109 150000->150001 rename. */
function resolveMigration(fn: string): string {
  const all = readdirSync(MIG);
  if (all.includes(fn)) return fn;
  const alt = fn.replace("20260620150000_l0b", "20260620150001_l0b");
  if (all.includes(alt)) return alt;
  throw new Error(`migration not found: ${fn}`);
}

function buildRegion(): string {
  const lines: string[] = [GEN_BEGIN];
  lines.push(
    "-- The dev DB builds ENTIRELY from seed.sql (tenant-scoped migrations no-op on",
    "-- reset, before seed creates the tenant). This region MIRRORS the per-row",
    "-- activation/correction migration bodies VERBATIM, in dependency order",
    "-- (taxonomy NODES -> activations/corrections -> short flips). Regenerate with",
    "-- `pnpm seed:regen-activations`; verified by the seed-activation-parity guard.",
    "-- MIRRORED (each = the identically-named migration body):",
  );
  for (const [name, fn] of MIRROR_LIST) lines.push(`--   ${name}  <-  ${resolveMigration(fn)}`);
  lines.push("--   (applier-managed blocks — l0-l2-activation, overlays, l1-q01-q07 — are NOT here; their tools own them.)");
  lines.push("");
  for (const [name, fn] of MIRROR_LIST) {
    const real = resolveMigration(fn);
    const body = readFileSync(path.join(MIG, real), "utf8").replace(/\s+$/, "");
    lines.push(`-- BEGIN ${name} (seed mirror of supabase/migrations/${real})`);
    lines.push(body);
    lines.push(`-- END ${name}`);
    lines.push("");
  }
  lines.push(GEN_END);
  return lines.join("\n");
}

function main(): void {
  let seed = readFileSync(SEED, "utf8");
  const region = buildRegion();

  const b = seed.indexOf(GEN_BEGIN);
  if (b !== -1) {
    // Replace existing generated region in place.
    const e = seed.indexOf(GEN_END, b);
    if (e === -1) throw new Error("GENERATED begin without end marker");
    seed = seed.slice(0, b) + region + seed.slice(e + GEN_END.length);
  } else {
    // First run: replace the hand-restored region if present (manifest sentinel ->
    // last block), else insert before the QA marker.
    const sentinel = "-- RESTORED ACTIVATION SEED-MIRRORS";
    const sIdx = seed.indexOf(sentinel);
    const lastEnd = "-- END l1-l4-short-eligible-backfill";
    const lIdx = seed.indexOf(lastEnd);
    if (sIdx !== -1 && lIdx !== -1) {
      // back up to the "-- ===" line that opens the restored manifest
      const start = seed.lastIndexOf("\n-- =", sIdx) + 1;
      const end = lIdx + lastEnd.length;
      seed = seed.slice(0, start) + region + "\n" + seed.slice(end + 1);
    } else {
      const m = QA_MARKER_RE.exec(seed);
      if (!m) throw new Error("QA marker not found");
      const at = m.index + 1;
      seed = seed.slice(0, at) + region + "\n\n" + seed.slice(at);
    }
  }
  writeFileSync(SEED, seed, { encoding: "utf8" });
  process.stdout.write(`[regen-seed-activations] wrote ${String(MIRROR_LIST.length)} mirror blocks into seed.sql\n`);
}

main();
