-- Atlas Assessment — 0A-Q15 activation (lane/l0a-taxonomy-activation, follow-up).
--
-- Founder supplied the compositing decision: place the single bowl crop (0A-15_1)
-- onto each shelf of the empty 3-shelf rack (0A-15_2) to make 3 CLICK_IMAGE_SINGLE
-- tiles (bowl on top / middle / bottom shelf); the child taps the BOTTOM one (t3).
-- Generated by gen_l0a_q15_tiles.py. Source-verified vs the doc page ("Tap the bowl
-- on the bottom shelf"). Uses the internal node l0a-geometry-6 "Positions" (created
-- in 20260620120000). Rebuilt content has no _authoring.requires_format_swap, so
-- is_active=true is atomic. short_test_eligible=true (key Short=Y). Idempotent;
-- mirrored in seed.sql. Non-destructive (only this id).

with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'CLICK_IMAGE_SINGLE'::question_format,
    content = '{"stem":"Tap the bowl on the bottom shelf.","tiles":[{"id":"t1","label":"Picture 1","image_path":"l0/sam-l0a-q15-t1.png","image_alt":"A rack of shelves with a bowl on one shelf."},{"id":"t2","label":"Picture 2","image_path":"l0/sam-l0a-q15-t2.png","image_alt":"A rack of shelves with a bowl on one shelf."},{"id":"t3","label":"Picture 3","image_path":"l0/sam-l0a-q15-t3.png","image_alt":"A rack of shelves with a bowl on one shelf."}],"_authoring":{"answer_model":{"rule":"select-one","correct":"t3"}}}'::jsonb,
    is_active = true, short_test_eligible = true,
    content_id = (select tc.id from tax_content tc where tc.tenant_id = t.id and tc.code = 'l0a-geometry-6')
from t where q.tenant_id = t.id and q.external_id = 'SAM-L0A-Q15';
