-- Atlas Assessment — L0 young-band QA fix batch #2 (lane/l0c-qa-fix-batch).
--
-- CONVERSION-only content corrections from a second QA play-through of the
-- short test (mixes L0B + L0C items in served order). ATLAS-owned defects
-- (multi-slot grading / picker level+length / fact-family prefill / raw-JSON
-- answer log) are handled separately and are NOT touched here.
--
-- Source-verified against the Level 0B/0C Placement Worksheet docx stems + the
-- per-question crops in scripts/conversion/source/0{b,c}/.
--
-- Fixes:
--   1. Trailing-scaffold trim — each word-problem stem ends at its question mark;
--      the redundant "Fill in the blanks / N op M = ___ / There are ___ ..."
--      worksheet scaffold is dropped (the single answer box already captures it).
--        SAM-L0B-Q14 (sushi)   SAM-L0B-Q15 (cookies)
--        SAM-L0C-Q09 (necklace) SAM-L0C-Q10 (birds)
--   3. Missing stimulus pictures wired (decorative-but-faithful; numbers are also
--      in the stem so image_required is safe with the bucket-upload gate):
--        SAM-L0B-Q15 -> l0/sam-l0b-q15.png  (crop 0b/0B-15.png)
--        SAM-L0C-Q09 -> l0/sam-l0c-q09.png  (crop 0c/0C-09.png)
--        SAM-L0C-Q10 -> l0/sam-l0c-q10.png  (gen_l0c_q10_birds.py composite)
--   4. SAM-L0C-Q05 (carrots, IMAGE_ORDERING) was authored with content.tiles in
--      the correct smallest->biggest order, so it served pre-sorted (nothing to
--      solve). The player renders content.tiles verbatim (ImageOrdering.tsx:
--      "may be shuffled by the author"), so the display order is reordered here
--      to t2,t3,t1; the correct answer (_authoring.answer_model.order) stays
--      t1,t2,t3 (grading is id-keyed, shuffle-safe).
--
-- Task 2 (number-line 30-36 labels) is an image-only change: the shared stimulus
-- l0/sam-l0c-q11.png is regenerated by gen_l0c_q11_stimulus.py and re-pointed in
-- activation-image-set.ts SOURCE_MAP; no row content changes (the Q11A-D rows
-- already reference that key).
--
-- Non-destructive: targeted UPDATEs by external_id (+ tenant); is_active / level /
-- short_test_eligible left untouched (carrots stays active). Idempotent. Mirrored
-- verbatim into supabase/seed.sql. AGENTS.md Section 11 parity: no-ops on dev
-- `supabase db reset` (tenant created later by seed.sql); the seed.sql mirror
-- applies it on the dev path; prod applies here.

-- 1+3) SAM-L0B-Q14 sushi — trim trailing "4 + 6 = ___" (image already wired).
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set content = '{"stem":"There are 4 pieces of sushi on a tray. There are 6 pieces of sushi in a box. How many pieces of sushi are there altogether?","correct_answer":"10","image_path":"l0/sam-l0b-q14.png","image_alt":"A tray of sushi and a box of sushi.","image_required":true}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0B-Q14';

-- 1+3) SAM-L0B-Q15 cookies — trim trailing scaffold + wire the cookies picture.
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set content = '{"stem":"Diana baked 10 cookies. Paul ate 7 cookies. How many cookies are left?","correct_answer":"3","image_path":"l0/sam-l0b-q15.png","image_alt":"A tray of cookies.","image_required":true}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0B-Q15';

-- 1+3) SAM-L0C-Q09 necklace — trim trailing scaffold + wire the necklace picture.
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set content = '{"stem":"There are 14 blue beads and 5 green beads on Sally''s necklace. How many beads are there altogether?","correct_answer":"19","image_path":"l0/sam-l0c-q09.png","image_alt":"A necklace with blue and green beads.","image_required":true}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q09';

-- 1+3) SAM-L0C-Q10 birds — trim trailing scaffold + wire the birds picture.
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set content = '{"stem":"There are 18 birds. 6 of the birds are blue. How many birds are yellow?","correct_answer":"12","image_path":"l0/sam-l0c-q10.png","image_alt":"A group of birds, some blue and some yellow.","image_required":true}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q10';

-- 4) SAM-L0C-Q05 carrots (IMAGE_ORDERING) — present the tiles shuffled away from
--    the correct order; correct order (_authoring.answer_model.order) unchanged.
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set content = '{"stem":"Put the pictures in order by size, from smallest to biggest.","tiles":[{"id":"t2","label":"Picture 2","image_path":"l0/sam-l0c-q05-t2.png","image_alt":"Second picture."},{"id":"t3","label":"Picture 3","image_path":"l0/sam-l0c-q05-t3.png","image_alt":"Third picture."},{"id":"t1","label":"Picture 1","image_path":"l0/sam-l0c-q05-t1.png","image_alt":"First picture."}],"_authoring":{"answer_model":{"rule":"order-equality","order":["t1","t2","t3"]}}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q05';
