-- Atlas Assessment — Defect C fix: SAM-L0C-Q13 days-of-week spelling.
-- (lane/young-band-content-fixes)
--
-- Founder decision: the four answer choices are the day WORDS rendered as image
-- tiles (Thursday / Friday / Saturday / Fryday); the child taps the correctly-
-- spelled missing day. Re-author from text MULTIPLE_CHOICE to CLICK_IMAGE_SINGLE
-- with the answer model in content._authoring (rule select-one, correct = the
-- "Friday" tile, t2). The "Fryday" tile is the spelling trap.
--
-- The four tile PNGs are generated by scripts/conversion/gen_l0c_q13_tiles.py
-- and uploaded to l0/sam-l0c-q13-t1..t4.png via upload-activation-images.ts
-- (added to its manifest in this lane). Per-tile minting reads
-- content.tiles[].image_path, so the row serves its tiles once uploaded.
--
-- The answer is keyed by tile ID (t2), not position, so a shuffling renderer is
-- fine. content._authoring carries ONLY answer_model (no requires_format_swap),
-- so the questions_held_rows_inactive guardrail permits this active row.
--
-- Non-destructive: a single targeted UPDATE WHERE external_id = 'SAM-L0C-Q13'
-- (+ tenant). is_active / level / short_test_eligible left untouched.
-- Idempotent. Mirrored verbatim into supabase/seed.sql. AGENTS.md Section 11
-- parity: no-ops on dev `supabase db reset` (tenant created later by seed.sql);
-- the seed.sql mirror applies it on the dev path; on prod the tenant exists.

with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'CLICK_IMAGE_SINGLE'::question_format,
    content = '{"stem":"Read the days of the week from Monday. One day is torn off: Monday, Tuesday, Wednesday, Thursday, ___, Saturday, Sunday. Tap the correctly spelled missing day.","tiles":[{"id":"t1","label":"Thursday","image_path":"l0/sam-l0c-q13-t1.png","image_alt":"The word Thursday."},{"id":"t2","label":"Friday","image_path":"l0/sam-l0c-q13-t2.png","image_alt":"The word Friday."},{"id":"t3","label":"Saturday","image_path":"l0/sam-l0c-q13-t3.png","image_alt":"The word Saturday."},{"id":"t4","label":"Fryday","image_path":"l0/sam-l0c-q13-t4.png","image_alt":"The word Fryday."}],"_authoring":{"answer_model":{"rule":"select-one","correct":"t2"}}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q13';
