-- Atlas Assessment — SAM-L0C-Q11 number line as 4 CLICK_IMAGE_SINGLE sub-items.
-- (lane/young-band-content-fixes)
--
-- ATLAS confirmed the shipped grader has no per-slot (multi-blank options)
-- mapping; the wired, faithful path is 4 independent single-selects. Source page
-- (Level 0C Placement Worksheet, task 11) + crop scripts/conversion/source/0c/
-- 0C-11.png: ONE bare number line (30-36, endpoints + ticks, no printed numerals)
-- with four sentences, each a two-option ORDERED pick. Authored as 4
-- CLICK_IMAGE_SINGLE rows that SHARE the number-line stimulus, each a clean
-- single-select (correct id == chosen id), keyed by id (shuffle-safe):
--
--   Q11A "31 comes ___ 30"   -> {After, Before}     correct After
--   Q11B "31 is ___ than 30"  -> {Greater, Smaller} correct Greater
--   Q11C "33 comes ___ 36"   -> {Before, After}     correct Before
--   Q11D "33 is ___ than 36"  -> {Smaller, Greater} correct Smaller
--
-- The 4 word-tiles (After/Before/Greater/Smaller) are generated by
-- scripts/conversion/gen_l0c_q11_tiles.py and REUSED across the sub-items
-- (After+Before for a/c; Greater+Smaller for b/d); uploaded via
-- upload-activation-images.ts. The shared stimulus is l0/sam-l0c-q11.png.
--
-- New rows inherit the original SAM-L0C-Q11 band: strand number_sense, level 0B,
-- content_id l0b-whole_numbers-1, short_test_eligible=true, is_active=true.
-- content._authoring carries ONLY answer_model (no requires_format_swap), so the
-- questions_held_rows_inactive guardrail permits an active row. The original
-- single SAM-L0C-Q11 is retired (is_active=false) by migration 20260618130300 so
-- it does not double-serve.
--
-- Additive (on conflict do nothing). Mirrored verbatim into supabase/seed.sql.
-- AGENTS.md Section 11 parity: no-ops on dev `supabase db reset` (tenant created
-- later by seed.sql); the seed.sql mirror loads it on the dev path; prod applies
-- here.

with t as (select id from tenants where slug = 'inspirea_singapore_math')
insert into questions
  (tenant_id, external_id, strand, level, difficulty, format,
   content, misconception_tags,
   word_count, operation_type, num_operations, representation,
   is_active, short_test_eligible, content_id)
select t.id, v.external_id, v.strand::strand, v.level::half_grade_level,
       v.difficulty, v.format::question_format,
       v.content::jsonb, v.misconception_tags,
       v.word_count, v.operation_type::operation_type, v.num_operations,
       v.representation::representation_kind,
       v.is_active, v.short_test_eligible,
       (select tc.id from tax_content tc
          where tc.tenant_id = t.id and tc.code = v.content_key)
from t,
  (values
    ('SAM-L0C-Q11A', 'number_sense', '0B', -1.8, 'CLICK_IMAGE_SINGLE',
     '{"stem":"Look at the number line. 31 comes ___ 30.","image_path":"l0/sam-l0c-q11.png","image_alt":"A number line with evenly spaced tick marks.","tiles":[{"id":"after","label":"After","image_path":"l0/sam-l0c-q11-after.png","image_alt":"The word After."},{"id":"before","label":"Before","image_path":"l0/sam-l0c-q11-before.png","image_alt":"The word Before."}],"_authoring":{"answer_model":{"rule":"select-one","correct":"after"}}}'::jsonb,
     array['NS_MAGNITUDE_MISJUDGE']::text[],
     9, 'IDENTIFY', 1, 'PICTORIAL', true, true, 'l0b-whole_numbers-1'),
    ('SAM-L0C-Q11B', 'number_sense', '0B', -1.8, 'CLICK_IMAGE_SINGLE',
     '{"stem":"Look at the number line. 31 is ___ than 30.","image_path":"l0/sam-l0c-q11.png","image_alt":"A number line with evenly spaced tick marks.","tiles":[{"id":"greater","label":"Greater","image_path":"l0/sam-l0c-q11-greater.png","image_alt":"The word Greater."},{"id":"smaller","label":"Smaller","image_path":"l0/sam-l0c-q11-smaller.png","image_alt":"The word Smaller."}],"_authoring":{"answer_model":{"rule":"select-one","correct":"greater"}}}'::jsonb,
     array['NS_MAGNITUDE_MISJUDGE']::text[],
     10, 'IDENTIFY', 1, 'PICTORIAL', true, true, 'l0b-whole_numbers-1'),
    ('SAM-L0C-Q11C', 'number_sense', '0B', -1.8, 'CLICK_IMAGE_SINGLE',
     '{"stem":"Look at the number line. 33 comes ___ 36.","image_path":"l0/sam-l0c-q11.png","image_alt":"A number line with evenly spaced tick marks.","tiles":[{"id":"before","label":"Before","image_path":"l0/sam-l0c-q11-before.png","image_alt":"The word Before."},{"id":"after","label":"After","image_path":"l0/sam-l0c-q11-after.png","image_alt":"The word After."}],"_authoring":{"answer_model":{"rule":"select-one","correct":"before"}}}'::jsonb,
     array['NS_MAGNITUDE_MISJUDGE']::text[],
     9, 'IDENTIFY', 1, 'PICTORIAL', true, true, 'l0b-whole_numbers-1'),
    ('SAM-L0C-Q11D', 'number_sense', '0B', -1.8, 'CLICK_IMAGE_SINGLE',
     '{"stem":"Look at the number line. 33 is ___ than 36.","image_path":"l0/sam-l0c-q11.png","image_alt":"A number line with evenly spaced tick marks.","tiles":[{"id":"smaller","label":"Smaller","image_path":"l0/sam-l0c-q11-smaller.png","image_alt":"The word Smaller."},{"id":"greater","label":"Greater","image_path":"l0/sam-l0c-q11-greater.png","image_alt":"The word Greater."}],"_authoring":{"answer_model":{"rule":"select-one","correct":"smaller"}}}'::jsonb,
     array['NS_MAGNITUDE_MISJUDGE']::text[],
     10, 'IDENTIFY', 1, 'PICTORIAL', true, true, 'l0b-whole_numbers-1')
  ) as v(external_id, strand, level, difficulty, format, content,
         misconception_tags, word_count, operation_type, num_operations,
         representation, is_active, short_test_eligible, content_key)
on conflict (tenant_id, external_id) do nothing;
