-- Atlas Assessment — L0 authoring overlay load (lane/l0-authoring).
--
-- Generated by scripts/conversion/apply-l0-overlay.ts from
-- scripts/conversion/overlay/l0{a,b,c}-authoring.json. Do not hand-edit.
--
-- Additive only: SAM-L0* inserts (on conflict do nothing) + UPDATEs that
-- re-band the 21 pipeline-loaded SAM-L0 rows from KA/KB to their true
-- 0A/0B/0C level and replace model-reconstructed content with
-- verbatim-from-source content. Requires the pre-K enum values added by
-- 20260616120000_add_prek_grade_levels.sql (separate migration).
--
-- Held image-tap rows (tap-one / tap-many / order pictures) carry
-- content._authoring.requires_format_swap=true + is_active=false and
-- satisfy the questions_held_rows_inactive CHECK (20260613120000). They are
-- NOT activated here (serve-time per-tile image minting is a later step).
--
-- AGENTS.md §11 parity: prod path. On dev `supabase db reset` this is a
-- no-op for inserts (runs before seed.sql creates the tenant); the identical
-- statements are mirrored into seed.sql in the l0-overlay block.

with t as (select id from tenants where slug = 'inspirea_singapore_math')
insert into questions
  (tenant_id, external_id, strand, level, difficulty, format,
   content, misconception_tags,
   word_count, operation_type, num_operations, representation,
   is_active, content_id)
select t.id, v.external_id, v.strand::strand, v.level::half_grade_level,
       v.difficulty, v.format::question_format,
       v.content::jsonb, v.misconception_tags,
       v.word_count, v.operation_type::operation_type, v.num_operations,
       v.representation::representation_kind,
       v.is_active,
       (select tc.id from tax_content tc
          where tc.tenant_id = t.id and tc.code = v.content_key)
from t,
  (values
    -- SAM-L0A-Q01 | inactive | blocker none-manual
    ('SAM-L0A-Q01', 'geometry', '0A', -2.5, 'MULTIPLE_CHOICE',
     '{"stem":"Help the rabbit get to the carrots. Draw a line from the rabbit to the carrots.","short_eligible":false,"_authoring":{"target_interaction":"click-image-single","blocker_code":"none-manual","held":true,"requires_format_swap":false}}'::jsonb,
     array[]::text[],
     14, 'IDENTIFY', 1, 'PICTORIAL', false, 'l0a-geometry-1'),

    -- SAM-L0A-Q02 | inactive | blocker none-manual
    ('SAM-L0A-Q02', 'geometry', '0A', -2.5, 'MULTIPLE_CHOICE',
     '{"stem":"Help the bee get to the flower. Draw a line from the bee to the flower.","short_eligible":false,"_authoring":{"target_interaction":"click-image-single","blocker_code":"none-manual","held":true,"requires_format_swap":false}}'::jsonb,
     array[]::text[],
     14, 'IDENTIFY', 1, 'PICTORIAL', false, 'l0a-geometry-1'),

    -- SAM-L0A-Q03 | held | blocker C
    ('SAM-L0A-Q03', 'geometry', '0A', -2.5, 'MULTIPLE_CHOICE',
     '{"stem":"Tap the big bowl.","short_eligible":true,"image_alt":"Two bowls of different sizes shown side by side.","_authoring":{"target_interaction":"click-image-single","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     4, 'IDENTIFY', 1, 'PICTORIAL', false, null),

    -- SAM-L0A-Q05 | held | blocker C
    ('SAM-L0A-Q05', 'geometry', '0A', -2.5, 'MULTIPLE_CHOICE',
     '{"stem":"Tap the thick book.","short_eligible":true,"image_alt":"Two books of different thicknesses shown side by side.","_authoring":{"target_interaction":"click-image-single","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     4, 'IDENTIFY', 1, 'PICTORIAL', false, null),

    -- SAM-L0A-Q06 | held | blocker C
    ('SAM-L0A-Q06', 'geometry', '0A', -2.5, 'MULTIPLE_CHOICE',
     '{"stem":"Tap the long branch.","short_eligible":true,"image_alt":"Two tree branches of different lengths shown side by side.","_authoring":{"target_interaction":"click-image-single","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     4, 'IDENTIFY', 1, 'PICTORIAL', false, null),

    -- SAM-L0A-Q07 | held | blocker C
    ('SAM-L0A-Q07', 'geometry', '0A', -2.5, 'MULTIPLE_CHOICE',
     '{"stem":"Tap the tall animal.","short_eligible":true,"image_alt":"Two animals of different heights shown side by side.","_authoring":{"target_interaction":"click-image-single","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     4, 'IDENTIFY', 1, 'PICTORIAL', false, null),

    -- SAM-L0A-Q09 | held | blocker C
    ('SAM-L0A-Q09', 'geometry', '0A', -2.5, 'MULTIPLE_CHOICE',
     '{"stem":"Draw an X to where you should put the pencil.","short_eligible":false,"image_alt":"Two boxes, one holding short pencils and one holding long pencils.","_authoring":{"target_interaction":"click-image-single","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     10, 'IDENTIFY', 1, 'PICTORIAL', false, null),

    -- SAM-L0A-Q10 | held | blocker C
    ('SAM-L0A-Q10', 'geometry', '0A', -2.5, 'MULTIPLE_CHOICE',
     '{"stem":"Tap the taller door.","short_eligible":true,"image_alt":"Two doors of different heights shown side by side.","_authoring":{"target_interaction":"click-image-single","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     4, 'IDENTIFY', 1, 'PICTORIAL', false, null),

    -- SAM-L0A-Q12 | held | blocker C
    ('SAM-L0A-Q12', 'geometry', '0A', -2.5, 'MULTIPLE_CHOICE',
     '{"stem":"Match each tail to the correct animal.","short_eligible":false,"image_alt":"A column of animals and a column of tails to be matched.","_authoring":{"target_interaction":"visual-matching","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     7, 'GEOMETRY', 1, 'PICTORIAL', false, 'l0a-geometry-2'),

    -- SAM-L0A-Q13 | held | blocker C
    ('SAM-L0A-Q13', 'geometry', '0A', -2.5, 'MULTIPLE_CHOICE',
     '{"stem":"Tap the bird facing left.","short_eligible":true,"image_alt":"Two birds facing different directions.","_authoring":{"target_interaction":"click-image-single","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     5, 'IDENTIFY', 1, 'PICTORIAL', false, null),

    -- SAM-L0A-Q14 | held | blocker C
    ('SAM-L0A-Q14', 'geometry', '0A', -2.5, 'MULTIPLE_CHOICE',
     '{"stem":"Tap the bird that is flying up.","short_eligible":true,"image_alt":"Two birds in flight in different directions.","_authoring":{"target_interaction":"click-image-single","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     7, 'IDENTIFY', 1, 'PICTORIAL', false, null),

    -- SAM-L0A-Q15 | held | blocker C
    ('SAM-L0A-Q15', 'geometry', '0A', -2.5, 'MULTIPLE_CHOICE',
     '{"stem":"Tap the bowl on the bottom shelf.","short_eligible":true,"image_alt":"A set of shelves with a bowl on each shelf.","_authoring":{"target_interaction":"click-image-single","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     7, 'IDENTIFY', 1, 'PICTORIAL', false, null),

    -- SAM-L0A-Q16 | inactive | blocker none-manual
    ('SAM-L0A-Q16', 'geometry', '0A', -2.5, 'MULTIPLE_CHOICE',
     '{"stem":"Draw a sweet outside the bowl.","short_eligible":false,"image_alt":"A bowl with space around it.","_authoring":{"target_interaction":"click-image-single","blocker_code":"none-manual","held":true,"requires_format_swap":false}}'::jsonb,
     array[]::text[],
     6, 'IDENTIFY', 1, 'PICTORIAL', false, null),

    -- SAM-L0A-Q18 | inactive | blocker none-oral
    ('SAM-L0A-Q18', 'geometry', '0A', -2.5, 'MULTIPLE_CHOICE',
     '{"stem":"Say the name of each shape.","short_eligible":false,"_authoring":{"target_interaction":"click-image-single","blocker_code":"none-oral","held":true,"requires_format_swap":false}}'::jsonb,
     array[]::text[],
     6, 'GEOMETRY', 1, 'SYMBOLIC', false, 'l0a-geometry-3'),

    -- SAM-L0B-Q01 | inactive_manual | blocker C
    ('SAM-L0B-Q01', 'number_sense', '0A', -2.1, 'MULTIPLE_CHOICE',
     '{"stem":"Look at the two pictures below. Circle 3 objects in Picture B that are not the same as the ones in Picture A.","short_eligible":false,"options":["option 1","option 2","option 3","option 4"],"correct_index":0,"_authoring":{"target_interaction":"click-image-multi","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     21, 'IDENTIFY', 1, 'PICTORIAL', false, null),

    -- SAM-L0B-Q03 | held_C | blocker C
    ('SAM-L0B-Q03', 'number_sense', '0A', -2.1, 'MULTIPLE_CHOICE',
     '{"stem":"Tap the part that is missing from the cake.","short_eligible":true,"options":["option 1","option 2","option 3","option 4"],"correct_index":0,"_authoring":{"target_interaction":"click-image-single","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     9, 'IDENTIFY', 1, 'PICTORIAL', false, 'l0a-geometry-2'),

    -- SAM-L0B-Q04 | held_C | blocker C
    ('SAM-L0B-Q04', 'number_sense', '0A', -2.1, 'MULTIPLE_CHOICE',
     '{"stem":"Start at X. Go right, up, left and down. Where are you? Tap the correct box below.","short_eligible":true,"options":["School","Bakery","Playground","Home"],"correct_index":1,"_authoring":{"target_interaction":"click-image-single","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     18, 'IDENTIFY', 1, 'PICTORIAL', false, null),

    -- SAM-L0B-Q06 | held_C | blocker C
    ('SAM-L0B-Q06', 'number_sense', '0A', -2.1, 'MULTIPLE_CHOICE',
     '{"stem":"Tap the numbers greater than 6.","short_eligible":true,"options":["option 1","option 2","option 3","option 4"],"correct_index":0,"_authoring":{"target_interaction":"select-multiple","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     6, 'PATTERN', 1, 'PICTORIAL', false, 'l0a-whole_numbers-1'),

    -- SAM-L0B-Q10 | active | blocker none
    ('SAM-L0B-Q10', 'operations_algorithms', '0A', -2.1, 'MULTIPLE_CHOICE',
     '{"stem":"There are 3 fish in a bowl and 5 fish in a tank. How many fish are there altogether? Tap your answer.","short_eligible":true,"options":["3","6","8"],"correct_index":2}'::jsonb,
     array[]::text[],
     22, 'ADDITION', 1, 'WORD_PROBLEM_SINGLE', true, 'l0a-whole_numbers-3'),

    -- SAM-L0B-Q11 | active | blocker none
    ('SAM-L0B-Q11', 'operations_algorithms', '0A', -2.1, 'MULTIPLE_CHOICE',
     '{"stem":"Mary put 7 items in a basket. She took out 3 items. How many items were left in the basket? Tap your answer.","short_eligible":true,"options":["4","2","6"],"correct_index":0}'::jsonb,
     array[]::text[],
     24, 'SUBTRACTION', 1, 'WORD_PROBLEM_SINGLE', true, 'l0a-whole_numbers-3'),

    -- SAM-L0B-Q12 | held_C | blocker C
    ('SAM-L0B-Q12', 'number_sense', '0A', -2.1, 'MULTIPLE_CHOICE',
     '{"stem":"Count on from 7. Help the bee find its way to its hive. Tap each number as you count.","short_eligible":false,"options":["option 1","option 2","option 3","option 4"],"correct_index":0,"_authoring":{"target_interaction":"click-image-multi","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     18, 'PATTERN', 1, 'PICTORIAL', false, 'l0a-whole_numbers-1'),

    -- SAM-L0B-Q13 | held_C | blocker C
    ('SAM-L0B-Q13', 'geometry', '0B', -2.1, 'MULTIPLE_CHOICE',
     '{"stem":"Color the animal in front of the mushrooms. Cross out the animal behind the mushrooms.","short_eligible":false,"options":["option 1","option 2","option 3","option 4"],"correct_index":0,"_authoring":{"target_interaction":"click-image","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     14, 'IDENTIFY', 1, 'PICTORIAL', false, 'l0b-geometry-1'),

    -- SAM-L0C-Q01 | held | blocker C
    ('SAM-L0C-Q01', 'number_sense', '0B', -2, 'MULTIPLE_CHOICE',
     '{"stem":"Match the birds to their positions.","options":["1st","2nd","3rd","4th","5th"],"correct_index":0,"short_eligible":false,"_authoring":{"target_interaction":"visual-matching","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     5, 'IDENTIFY', 1, 'PICTORIAL', false, 'l0b-whole_numbers-4'),

    -- SAM-L0C-Q02 | held | blocker none-manual
    ('SAM-L0C-Q02', 'number_sense', '0B', -2, 'MULTIPLE_CHOICE',
     '{"stem":"Show numbers that make 9. Color some leaves green. Color the rest red. Write the numbers in the number bond.","options":["option 1","option 2","option 3","option 4"],"correct_index":0,"short_eligible":false,"_authoring":{"target_interaction":"manual","blocker_code":"none-manual","held":true,"requires_format_swap":false}}'::jsonb,
     array[]::text[],
     19, 'IDENTIFY', 1, 'PICTORIAL', false, 'l0b-whole_numbers-2'),

    -- SAM-L0C-Q04 | held | blocker C
    ('SAM-L0C-Q04', 'number_sense', '0B', -2, 'MULTIPLE_CHOICE',
     '{"stem":"Complete the fact family.","options":["6","3","9"],"correct_index":2,"short_eligible":true,"_authoring":{"target_interaction":"equation-set","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     4, 'ADDITION', 1, 'SYMBOLIC', false, 'l0b-whole_numbers-3'),

    -- SAM-L0C-Q06 | held | blocker C
    ('SAM-L0C-Q06', 'number_sense', '0B', -2, 'MULTIPLE_CHOICE',
     '{"stem":"Look at the color pattern below. Color the squares to complete the pattern.","options":["option 1","option 2","option 3","option 4"],"correct_index":0,"short_eligible":false,"_authoring":{"target_interaction":"multi-blank","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     12, 'PATTERN', 1, 'PICTORIAL', false, 'l0b-geometry-4'),

    -- SAM-L0C-Q07 | held | blocker none-manual
    ('SAM-L0C-Q07', 'geometry', '0B', -2, 'MULTIPLE_CHOICE',
     '{"stem":"Draw a shape in each box. Shape with 4 sides / Shape with no sides / Shape with 3 sides.","options":["option 1","option 2","option 3","option 4"],"correct_index":0,"short_eligible":false,"_authoring":{"target_interaction":"manual","blocker_code":"none-manual","held":true,"requires_format_swap":false}}'::jsonb,
     array[]::text[],
     18, 'GEOMETRY', 1, 'PICTORIAL', false, 'l0b-geometry-2'),

    -- SAM-L0C-Q12 | held | blocker C
    ('SAM-L0C-Q12', 'geometry', '0B', -2, 'MULTIPLE_CHOICE',
     '{"stem":"Tap the objects that look like a cube in the picture below.","options":["option 1","option 2","option 3","option 4"],"correct_index":0,"short_eligible":false,"_authoring":{"target_interaction":"click-image-multi","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb,
     array[]::text[],
     11, 'GEOMETRY', 1, 'PICTORIAL', false, 'l0b-geometry-3')
  ) as v(external_id, strand, level, difficulty, format, content,
         misconception_tags, word_count, operation_type, num_operations,
         representation, is_active, content_key)
on conflict (tenant_id, external_id) do nothing;

-- SAM-L0A-Q04: inactive (click-image-single, blocker none-manual)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0A'::half_grade_level,
    format = 'MULTIPLE_CHOICE'::question_format,
    is_active = false,
    content = '{"stem":"Color the shapes red. Color the shapes blue. Color the shapes green.","short_eligible":false,"_authoring":{"target_interaction":"click-image-single","blocker_code":"none-manual","held":true,"requires_format_swap":false}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0A-Q04';

-- SAM-L0A-Q08: held (click-image-single, blocker C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0A'::half_grade_level,
    format = 'MULTIPLE_CHOICE'::question_format,
    is_active = false,
    content = '{"stem":"Tap the object that is the same as the one in the box.","short_eligible":true,"image_alt":"An object shown inside a box, with several objects to choose from below.","_authoring":{"target_interaction":"click-image-single","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0A-Q08';

-- SAM-L0A-Q11: held (click-image-single, blocker C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0A'::half_grade_level,
    format = 'MULTIPLE_CHOICE'::question_format,
    is_active = false,
    content = '{"stem":"Look at the pattern below. Tap what comes next.","short_eligible":true,"image_alt":"A repeating pattern of flowers with the last item missing, and flower choices to tap.","_authoring":{"target_interaction":"click-image-single","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0A-Q11';

-- SAM-L0A-Q17: held (single-MC, blocker A)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0A'::half_grade_level,
    format = 'MULTIPLE_CHOICE'::question_format,
    is_active = false,
    content = '{"stem":"Count the balloons. Tap the number.","short_eligible":true,"options":["6","5","2"],"correct_index":1,"image_alt":"A group of balloons.","_authoring":{"target_interaction":"single-MC","blocker_code":"A","held":true,"requires_format_swap":false}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0A-Q17';

-- SAM-L0B-Q02: held_C (click-image-single, blocker C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0A'::half_grade_level,
    format = 'MULTIPLE_CHOICE'::question_format,
    is_active = false,
    content = '{"stem":"Tap the object that comes next in the pattern below.","short_eligible":true,"options":["option 1","option 2","option 3","option 4"],"correct_index":0,"_authoring":{"target_interaction":"click-image-single","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0B-Q02';

-- SAM-L0B-Q05: held_C (multi-blank, blocker C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0A'::half_grade_level,
    format = 'MULTIPLE_CHOICE'::question_format,
    is_active = false,
    content = '{"stem":"Count back from 10. Write the missing numbers.","short_eligible":false,"options":["option 1","option 2","option 3","option 4"],"correct_index":0,"_authoring":{"target_interaction":"multi-blank","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0B-Q05';

-- SAM-L0B-Q07: held_A (single-MC, blocker A)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0A'::half_grade_level,
    format = 'MULTIPLE_CHOICE'::question_format,
    is_active = false,
    content = '{"stem":"How are the shapes sorted?","short_eligible":true,"options":["color","size"],"correct_index":0,"image_alt":"Two boxes, each holding a group of shapes.","_authoring":{"target_interaction":"single-MC","blocker_code":"A","held":true,"requires_format_swap":false}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0B-Q07';

-- SAM-L0B-Q08: held_C (multi-blank, blocker C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0A'::half_grade_level,
    format = 'MULTIPLE_CHOICE'::question_format,
    is_active = false,
    content = '{"stem":"Read. Write the missing numbers. I have ___ toy cars. I have ___ big toy car and ___ small toy cars.","short_eligible":false,"options":["option 1","option 2","option 3","option 4"],"correct_index":0,"_authoring":{"target_interaction":"multi-blank","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0B-Q08';

-- SAM-L0B-Q09: active (numeric-single, blocker none)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0A'::half_grade_level,
    format = 'NUMERIC_ENTRY'::question_format,
    is_active = true,
    content = '{"stem":"There are 8 candy. There are 5 candy in the bag. How many candy go in the jar?","short_eligible":false,"correct_answer":"3"}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0B-Q09';

-- SAM-L0B-Q14: active (numeric-single, blocker none)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0B'::half_grade_level,
    format = 'NUMERIC_ENTRY'::question_format,
    is_active = true,
    content = '{"stem":"There are 4 pieces of sushi on a tray. There are 6 pieces of sushi in a box. How many pieces of sushi are there altogether? Fill in the blanks. 4 + 6 = ___ There are ___ pieces of sushi altogether.","short_eligible":true,"correct_answer":"10"}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0B-Q14';

-- SAM-L0B-Q15: active (numeric-single, blocker none)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0B'::half_grade_level,
    format = 'NUMERIC_ENTRY'::question_format,
    is_active = true,
    content = '{"stem":"Diana baked 10 cookies. Paul ate 7 cookies. How many cookies are left? Fill in the blanks. 10 - 7 = ___ There are ___ cookies left.","short_eligible":true,"correct_answer":"3"}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0B-Q15';

-- SAM-L0C-Q03: held (select-multiple, blocker C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0B'::half_grade_level,
    format = 'MULTIPLE_CHOICE'::question_format,
    is_active = false,
    content = '{"stem":"Tap the boxes that make 10.","options":["5 + 5","3 + 7","2 + 8","2 + 2","1 + 9","3 + 5","9 + 2","6 + 4"],"correct_index":0,"short_eligible":true,"_authoring":{"target_interaction":"select-multiple","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q03';

-- SAM-L0C-Q05: held (multi-blank, blocker C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0B'::half_grade_level,
    format = 'MULTIPLE_CHOICE'::question_format,
    is_active = false,
    content = '{"stem":"Write numbers: 1 = smallest, 2 = bigger, 3 = biggest in the correct blanks.","options":["smallest","bigger","biggest"],"correct_index":1,"short_eligible":true,"_authoring":{"target_interaction":"multi-blank","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q05';

-- SAM-L0C-Q08: held (multi-blank, blocker C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0B'::half_grade_level,
    format = 'MULTIPLE_CHOICE'::question_format,
    is_active = false,
    content = '{"stem":"Skip count by 2s. Fill in the missing numbers.","options":["4","8","16","20"],"correct_index":0,"short_eligible":true,"_authoring":{"target_interaction":"multi-blank","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q08';

-- SAM-L0C-Q09: active (numeric-single, blocker none)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0B'::half_grade_level,
    format = 'NUMERIC_ENTRY'::question_format,
    is_active = true,
    content = '{"stem":"There are 14 blue beads and 5 green beads on Sally''s necklace. How many beads are there altogether? 14 + 5 = ___. There are ___ beads altogether.","correct_answer":"19","short_eligible":true}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q09';

-- SAM-L0C-Q10: active (numeric-single, blocker none)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0B'::half_grade_level,
    format = 'NUMERIC_ENTRY'::question_format,
    is_active = true,
    content = '{"stem":"There are 18 birds. 6 of the birds are blue. How many birds are yellow? Fill in the blanks. 18 - 6 = ___ There are ___ yellow birds.","correct_answer":"12","short_eligible":true}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q10';

-- SAM-L0C-Q11: held (multi-blank, blocker C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0B'::half_grade_level,
    format = 'MULTIPLE_CHOICE'::question_format,
    is_active = false,
    content = '{"stem":"Look at the number line. Tap on the answers. 31 comes ___ 30. 31 is ___ than 30. 33 comes ___ 36. 33 is ___ than 36.","options":["after","greater","before","smaller"],"correct_index":0,"short_eligible":true,"_authoring":{"target_interaction":"multi-blank","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q11';

-- SAM-L0C-Q13: active (single-MC, blocker none)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0B'::half_grade_level,
    format = 'MULTIPLE_CHOICE'::question_format,
    is_active = true,
    content = '{"stem":"Read aloud the days of the week from Monday. A part of the page is torn. What is the missing day? Tap your answer.","options":["Friday","Fryday","Thursday","Saturday"],"correct_index":0,"short_eligible":true}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q13';

-- SAM-L0C-Q14: held (numeric-single, blocker A)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0C'::half_grade_level,
    format = 'NUMERIC_ENTRY'::question_format,
    is_active = false,
    content = '{"stem":"How many pairs of the same bikes are there? Write the number.","correct_answer":"4","image_alt":"A picture showing several motorcycles in different colors.","short_eligible":true,"_authoring":{"target_interaction":"numeric-single","blocker_code":"A","held":true,"requires_format_swap":false}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q14';

-- SAM-L0C-Q15: held (select-multiple, blocker C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0C'::half_grade_level,
    format = 'MULTIPLE_CHOICE'::question_format,
    is_active = false,
    content = '{"stem":"Tap the circles with odd numbers.","options":["1","10","26","5","12","24","35","41","40"],"correct_index":0,"short_eligible":true,"_authoring":{"target_interaction":"select-multiple","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q15';

-- SAM-L0C-Q16: held (multi-blank, blocker C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set level = '0C'::half_grade_level,
    format = 'MULTIPLE_CHOICE'::question_format,
    is_active = false,
    content = '{"stem":"Break apart 32. Fill in the boxes.","options":["30","2"],"correct_index":0,"short_eligible":true,"_authoring":{"target_interaction":"multi-blank","blocker_code":"C","held":true,"requires_format_swap":true}}'::jsonb
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q16';

