-- Atlas Assessment — L0/L1/L2 held-row activation (lane/l0-l2-activation).
--
-- Generated by scripts/conversion/apply-activation.ts from the per-level
-- overlay/l*-activation.json files. Do not hand-edit.
--
-- Atomic activation of flip-ready held rows after #71 (image formats) + #77
-- (per-tile minting): each UPDATE sets the real format + full render/answer
-- content + is_active=true, guarded on is_active=false (idempotent). The
-- activated content carries no _authoring.requires_format_swap, so the
-- questions_held_rows_inactive CHECK permits is_active=true.
--
-- AGENTS.md §11 parity: prod path; identical statements mirrored into
-- seed.sql in the l0-l2-activation block (idempotent guards).
--
-- PRECONDITION: the per-question images in the upload manifest must be in the
-- private question-images bucket before this runs live, or an activated
-- image row 500s at serve (signed-URL mint throws on a missing object).

-- SAM-L0A-Q08 → CLICK_IMAGE_SINGLE (level 0A)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'CLICK_IMAGE_SINGLE'::question_format,
    content = '{"stem":"Tap the object that is the same as the one in the box.","tiles":[{"id":"t1","label":"Picture 1","image_path":"l0/sam-l0a-q08-t1.png","image_alt":"First object choice."},{"id":"t2","label":"Picture 2","image_path":"l0/sam-l0a-q08-t2.png","image_alt":"Second object choice."},{"id":"t3","label":"Picture 3","image_path":"l0/sam-l0a-q08-t3.png","image_alt":"Third object choice."},{"id":"t4","label":"Picture 4","image_path":"l0/sam-l0a-q08-t4.png","image_alt":"Fourth object choice."}],"_authoring":{"answer_model":{"rule":"select-one","correct":"t4"}}}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0A-Q08'
  and q.is_active = false;

-- SAM-L0A-Q11 → CLICK_IMAGE_SINGLE (level 0A)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'CLICK_IMAGE_SINGLE'::question_format,
    content = '{"stem":"Look at the pattern below. Tap what comes next.","tiles":[{"id":"t1","label":"Picture 1","image_path":"l0/sam-l0a-q11-t1.png","image_alt":"First flower choice."},{"id":"t2","label":"Picture 2","image_path":"l0/sam-l0a-q11-t2.png","image_alt":"Second flower choice."}],"_authoring":{"answer_model":{"rule":"select-one","correct":"t2"}}}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0A-Q11'
  and q.is_active = false;

-- SAM-L0B-Q02 → CLICK_IMAGE_SINGLE (level 0B)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'CLICK_IMAGE_SINGLE'::question_format,
    content = '{"stem":"Tap the object that comes next in the pattern below.","tiles":[{"id":"t1","label":"Picture 1","image_path":"l0/sam-l0b-q02-t1.png","image_alt":"First object choice."},{"id":"t2","label":"Picture 2","image_path":"l0/sam-l0b-q02-t2.png","image_alt":"Second object choice."},{"id":"t3","label":"Picture 3","image_path":"l0/sam-l0b-q02-t3.png","image_alt":"Third object choice."},{"id":"t4","label":"Picture 4","image_path":"l0/sam-l0b-q02-t4.png","image_alt":"Fourth object choice."}],"_authoring":{"answer_model":{"rule":"select-one","correct":"t4"}}}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0B-Q02'
  and q.is_active = false;

-- SAM-L0C-Q03 → SELECT_MULTIPLE (level 0C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'SELECT_MULTIPLE'::question_format,
    content = '{"stem":"Tap the boxes that make 10.","select_rule":"all","options":[{"id":"o1","label":"5 + 5"},{"id":"o2","label":"3 + 7"},{"id":"o3","label":"2 + 8"},{"id":"o4","label":"2 + 2"},{"id":"o5","label":"1 + 9"},{"id":"o6","label":"3 + 5"},{"id":"o7","label":"9 + 2"},{"id":"o8","label":"6 + 4"}],"correct":["o1","o2","o3","o5","o8"]}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q03'
  and q.is_active = false;

-- SAM-L0C-Q04 → EQUATION_SET (level 0C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'EQUATION_SET'::question_format,
    content = '{"stem":"Complete the fact family.","rows":4,"answer_rule":"set-equality","canonical":[{"a":6,"op":"+","b":3,"result":9},{"a":3,"op":"+","b":6,"result":9},{"a":9,"op":"-","b":3,"result":6},{"a":9,"op":"-","b":6,"result":3}],"allowCommutative":true}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q04'
  and q.is_active = false;

-- SAM-L0C-Q08 → MULTI_BLANK (level 0C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'MULTI_BLANK'::question_format,
    content = '{"stem":"Skip count by 2s. Fill in the missing numbers.","tokens":[{"t":"text","value":"2,"},{"t":"blank","id":"b1"},{"t":"text","value":", 6,"},{"t":"blank","id":"b2"},{"t":"text","value":", 10, 12, 14,"},{"t":"blank","id":"b3"},{"t":"text","value":", 18,"},{"t":"blank","id":"b4"}],"blanks":{"b1":{"value":"4","numeric":true},"b2":{"value":"8","numeric":true},"b3":{"value":"16","numeric":true},"b4":{"value":"20","numeric":true}}}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q08'
  and q.is_active = false;

-- SAM-L0C-Q11 → MULTI_BLANK (level 0C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'MULTI_BLANK'::question_format,
    content = '{"stem":"Look at the number line. Tap on the answers.","image_path":"l0/sam-l0c-q11.png","image_alt":"A number line with evenly spaced tick marks.","tokens":[{"t":"text","value":"31 comes"},{"t":"blank","id":"b1"},{"t":"text","value":"30. 31 is"},{"t":"blank","id":"b2"},{"t":"text","value":"than 30. 33 comes"},{"t":"blank","id":"b3"},{"t":"text","value":"36. 33 is"},{"t":"blank","id":"b4"},{"t":"text","value":"than 36."}],"blanks":{"b1":{"value":"after","numeric":false},"b2":{"value":"greater","numeric":false},"b3":{"value":"before","numeric":false},"b4":{"value":"smaller","numeric":false}}}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q11'
  and q.is_active = false;

-- SAM-L0C-Q14 → NUMERIC_ENTRY (level 0C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'NUMERIC_ENTRY'::question_format,
    content = '{"stem":"How many pairs of the same bikes are there? Write the number.","correct_answer":"4","image_path":"l0/sam-l0c-q14.png","image_alt":"A picture showing several motorcycles in different colors.","image_required":true}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q14'
  and q.is_active = false;

-- SAM-L0C-Q16 → MULTI_BLANK (level 0C)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'MULTI_BLANK'::question_format,
    content = '{"stem":"Break apart 32. Fill in the boxes.","tokens":[{"t":"text","value":"32 ="},{"t":"blank","id":"b1"},{"t":"text","value":"+"},{"t":"blank","id":"b2"}],"blanks":{"b1":{"value":"30","numeric":true},"b2":{"value":"2","numeric":true}}}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L0C-Q16'
  and q.is_active = false;

-- SAM-L1-Q02 → MULTIPLE_CHOICE (level KA)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'MULTIPLE_CHOICE'::question_format,
    content = '{"stem":"Click on the bigger animal.","options":["the elephant","the bear"],"correct_index":0,"image_path":"l1/sam-l1-q02.png","image_alt":"Two animals shown side by side for a size comparison.","image_required":true}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L1-Q02'
  and q.is_active = false;

-- SAM-L1-Q03 → MULTIPLE_CHOICE (level KA)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'MULTIPLE_CHOICE'::question_format,
    content = '{"stem":"Which is longer, the toy car or the toy plane?","options":["the toy car","the toy plane"],"correct_index":1,"image_path":"l1/sam-l1-q03.png","image_alt":"A toy and another toy shown for a length comparison.","image_required":true}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L1-Q03'
  and q.is_active = false;

-- SAM-L1-Q11 → VISUAL_MATCHING (level KA)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'VISUAL_MATCHING'::question_format,
    content = '{"stem":"Match each number to its number word.","left":[{"id":"n1","label":"1"},{"id":"n2","label":"2"},{"id":"n3","label":"3"},{"id":"n4","label":"4"},{"id":"n5","label":"5"},{"id":"n6","label":"6"},{"id":"n7","label":"7"},{"id":"n8","label":"8"},{"id":"n9","label":"9"},{"id":"n10","label":"10"}],"right":[{"id":"w1","label":"one"},{"id":"w2","label":"two"},{"id":"w3","label":"three"},{"id":"w4","label":"four"},{"id":"w5","label":"five"},{"id":"w6","label":"six"},{"id":"w7","label":"seven"},{"id":"w8","label":"eight"},{"id":"w9","label":"nine"},{"id":"w10","label":"ten"}],"pairs":{"n1":"w1","n2":"w2","n3":"w3","n4":"w4","n5":"w5","n6":"w6","n7":"w7","n8":"w8","n9":"w9","n10":"w10"}}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L1-Q11'
  and q.is_active = false;

-- SAM-L1-Q13 → VISUAL_MATCHING (level KA)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'VISUAL_MATCHING'::question_format,
    content = '{"stem":"Match each shape to its name: rectangle, circle, square, triangle.","left":[{"id":"sl1","label":"Shape 1","image_path":"l1/sam-l1-q13-circle.png","image_alt":"A coloured 2D shape."},{"id":"sl2","label":"Shape 2","image_path":"l1/sam-l1-q13-rectangle.png","image_alt":"A coloured 2D shape."},{"id":"sl3","label":"Shape 3","image_path":"l1/sam-l1-q13-square.png","image_alt":"A coloured 2D shape."},{"id":"sl4","label":"Shape 4","image_path":"l1/sam-l1-q13-triangle.png","image_alt":"A coloured 2D shape."}],"right":[{"id":"nr1","label":"circle"},{"id":"nr2","label":"rectangle"},{"id":"nr3","label":"square"},{"id":"nr4","label":"triangle"}],"pairs":{"sl1":"nr1","sl2":"nr2","sl3":"nr3","sl4":"nr4"}}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L1-Q13'
  and q.is_active = false;

-- SAM-L1-Q14 → MULTI_BLANK (level KA)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'MULTI_BLANK'::question_format,
    content = '{"stem":"___ apples and ___ apples make 8 apples.","tokens":[{"t":"blank","id":"b1"},{"t":"text","value":" apples and "},{"t":"blank","id":"b2"},{"t":"text","value":" apples make 8 apples."}],"blanks":{"b1":{"value":"5","numeric":true},"b2":{"value":"3","numeric":true}},"image_path":"l1/sam-l1-q14.png","image_alt":"Two boxes, each holding some apples.","image_required":true}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L1-Q14'
  and q.is_active = false;

-- SAM-L1-Q15 → VISUAL_MATCHING (level KA)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'VISUAL_MATCHING'::question_format,
    content = '{"stem":"Match each solid to its name: sphere, cylinder, cube, cone.","left":[{"id":"sl1","label":"Solid 1","image_path":"l1/sam-l1-q15-sphere.png","image_alt":"A coloured 3D solid."},{"id":"sl2","label":"Solid 2","image_path":"l1/sam-l1-q15-cylinder.png","image_alt":"A coloured 3D solid."},{"id":"sl3","label":"Solid 3","image_path":"l1/sam-l1-q15-cube.png","image_alt":"A coloured 3D solid."},{"id":"sl4","label":"Solid 4","image_path":"l1/sam-l1-q15-cone.png","image_alt":"A coloured 3D solid."}],"right":[{"id":"nr1","label":"sphere"},{"id":"nr2","label":"cylinder"},{"id":"nr3","label":"cube"},{"id":"nr4","label":"cone"}],"pairs":{"sl1":"nr1","sl2":"nr2","sl3":"nr3","sl4":"nr4"}}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L1-Q15'
  and q.is_active = false;

-- SAM-L1-Q16 → MULTIPLE_CHOICE (level KB)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'MULTIPLE_CHOICE'::question_format,
    content = '{"stem":"Who is in front of the tree, Louis or Andy?","options":["Louis","Andy"],"correct_index":1,"image_path":"l1/sam-l1-q16.png","image_alt":"A scene with a tree and two children standing in it.","image_required":true}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L1-Q16'
  and q.is_active = false;

-- SAM-L1-Q17 → IMAGE_ORDERING (level KB)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'IMAGE_ORDERING'::question_format,
    content = '{"stem":"The pictures show what Tom does in one day. Put them in order from first to last.","tiles":[{"id":"t1","label":"Picture 1","image_path":"l1/sam-l1-q17-brushing-teeth.png","image_alt":"A picture of part of a child''s day."},{"id":"t2","label":"Picture 2","image_path":"l1/sam-l1-q17-walking-to-school.png","image_alt":"A picture of part of a child''s day."},{"id":"t3","label":"Picture 3","image_path":"l1/sam-l1-q17-studying.png","image_alt":"A picture of part of a child''s day."},{"id":"t4","label":"Picture 4","image_path":"l1/sam-l1-q17-sleeping.png","image_alt":"A picture of part of a child''s day."}],"_authoring":{"answer_model":{"rule":"order-equality","order":["t1","t2","t3","t4"]}}}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L1-Q17'
  and q.is_active = false;

-- SAM-L1-Q27 → VISUAL_MATCHING (level 1B)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'VISUAL_MATCHING'::question_format,
    content = '{"stem":"Match each number to its number word.","left":[{"id":"n11","label":"11"},{"id":"n12","label":"12"},{"id":"n13","label":"13"},{"id":"n20","label":"20"}],"right":[{"id":"w11","label":"eleven"},{"id":"w12","label":"twelve"},{"id":"w13","label":"thirteen"},{"id":"w20","label":"twenty"}],"pairs":{"n11":"w11","n12":"w12","n13":"w13","n20":"w20"}}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L1-Q27'
  and q.is_active = false;

-- SAM-L2-Q06 → CLICK_IMAGE_SINGLE (level 1A)
with t as (select id from tenants where slug = 'inspirea_singapore_math')
update questions q
set format = 'CLICK_IMAGE_SINGLE'::question_format,
    content = '{"stem":"Which picture shows 37?","tiles":[{"id":"t1","label":"Picture 1","image_path":"l2/sam-l2-q06-opt1.png","image_alt":"Base-ten blocks: loose ones only."},{"id":"t2","label":"Picture 2","image_path":"l2/sam-l2-q06-opt2.png","image_alt":"Base-ten blocks: several ten-rods."},{"id":"t3","label":"Picture 3","image_path":"l2/sam-l2-q06-opt3.png","image_alt":"Base-ten blocks: some ten-rods and some loose ones."},{"id":"t4","label":"Picture 4","image_path":"l2/sam-l2-q06-opt4.png","image_alt":"Base-ten blocks: some ten-rods and some loose ones."}],"_authoring":{"answer_model":{"rule":"select-one","correct":"t3"}}}'::jsonb,
    is_active = true
from t
where q.tenant_id = t.id
  and q.external_id = 'SAM-L2-Q06'
  and q.is_active = false;

